#!/usr/bin/env python3

import time
from pathlib import Path
import argparse
import requests
import textwrap
import sys
import numpy as np
import copy

from tensor_viterbi import HSMM, FastaReader
from tensor_viterbi.viterbi import decode_tensor_viterbi_omp

API_URL = "https://api.genome.ucsc.edu/getData/sequence" # UCSC REST API for fetching genomic sequences
OBS_LIMIT = None                                         # max observations read from FASTA (None = whole file)
_BASES = ["A", "T", "C", "G"]

# Approximate euchromatic MSY boundaries.
# - PAR1 end  -> start of euchromatic MSY
# - Yq12 het. -> end of euchromatic MSY
# NOTE: the centromere lies inside this interval; in hg19 it is a gap (Ns),
REGIONS = {
    "hs1": {            # T2T-CHM13 v2.0
        "chrom": "chrY",
        "start": 2_458_320,   # end of PAR1 (Rhie et al. 2023)
        "end":   26_673_214,  # start of Yq12 heterochromatin
        "label": "T2T-CHM13v2.0_chrY_euchromatic_MSY",
    },
}


#! -------------------------------------------------------------
#!
#! UTILITIES, maybe I'll need to create a library fire for these
#!
#! -------------------------------------------------------------



def _read_obs_gene(fasta_path: Path, limit: int | None = None) -> np.ndarray:
    reader = FastaReader(fasta_path, symbols=_BASES)
    obs = reader.read()
    if limit is not None:
        obs = obs[:limit]
    return obs.astype(int)


def write_gene(states: np.ndarray, fasta_path: Path, out_path: Path) -> None:

    with open(out_path, "w") as f:
        f.write(f"# Gene structure predictions | source: {fasta_path.name} | generated by tensor-viterbi\n")
        flat = states.astype(int)
        for i in range(0, len(flat), 30):
            f.write("".join(str(s) for s in flat[i:i + 30]) + "\n")


def fetch_sequence(genome: str, chrom: str, start: int, end: int) -> str:

    params = {"genome": genome, "chrom": chrom, "start": start, "end": end}
    print(f"[info] Requesting {chrom}:{start}-{end} from {genome} ...",
          file=sys.stderr)
    r = requests.get(API_URL, params=params, timeout=300)
    r.raise_for_status()
    data = r.json()
    if "dna" not in data:
        raise RuntimeError(f"Unexpected response: {data}")
    return data["dna"]


def write_fasta(path: Path, header: str, sequence: str, width: int = 60) -> None:
    """Write a single-record FASTA, wrapping the sequence at `width` columns."""
    with path.open("w") as fh:
        fh.write(f">{header}\n")
        for line in textwrap.wrap(sequence, width=width):
            fh.write(line + "\n")


#! -------------------------------------------------------------
#!
#! HSMM Setup and Gene Prediction
#!
#! -------------------------------------------------------------


def gene_hsmm_loader(fasta_path: Path, N: int = 2, D: int = 1000,
                     limit: int | None = OBS_LIMIT) -> HSMM:

    print(f"Loading Chromosome: {fasta_path}")

    obs_seq = _read_obs_gene(fasta_path, limit=limit)

    trans_mat = np.full((N, N), 1.0 / N)

    # Emission probs (O x N): order follows _BASES = ["A", "T", "C", "G"]
    # State 0 Intergenic: very AT-rich (A=0.35, T=0.35, C=0.15, G=0.15)
    # State 1 Exon:       GC-rich      (A=0.20, T=0.20, C=0.30, G=0.30)
    # State 2 Intron:     AT-rich      (A=0.30, T=0.30, C=0.20, G=0.20)
    intergenic_emit = np.array([0.35, 0.35, 0.15, 0.15])
    exon_emit       = np.array([0.20, 0.20, 0.30, 0.30])
    intron_emit     = np.array([0.30, 0.30, 0.20, 0.20])
    emission_probs = np.column_stack([intergenic_emit, exon_emit, intron_emit])

    duration_probs = np.full((D, N), 1.0 / D)
    start_probs = np.full(N, 1.0 / N)

    states = ["Intergenic", "Exon", "Intron"]

    return (
        HSMM(states)
        .set_emissions(_BASES, emission_probs)
        .set_transitions(trans_mat)
        .set_duration_probs(duration_probs)
        .set_start_probs(start_probs)
        .set_observations(obs_seq)
    )



def reestimate_hsmm(gene_hsmm: HSMM, result: np.ndarray) -> HSMM:
    """Re-estimate HSMM parameters from a Viterbi-decoded state sequence.

    Computes new emission, transition, and duration probabilities by counting
    statistics directly from the decoded path, then normalizing.
    Returns a new HSMM in linear probability space ready for the next iteration.
    """

    N       = len(gene_hsmm.states)
    O       = len(gene_hsmm.emissions)
    D       = gene_hsmm.duration_probs_linear.shape[0]
    obs_seq = gene_hsmm.obs_seq.astype(int)
    T       = len(obs_seq)

    # Parse decoded path into (state, start_t, length) segments
    segments: list[tuple[int, int, int]] = []
    t = 0
    while t < T:
        s = int(result[t])
        length = 1
        while t + length < T and int(result[t + length]) == s:
            length += 1
        segments.append((s, t, length))
        t += length

    # Emission counts: how many nucleotides of symbol o are in state n
    emit_counts = np.zeros((O, N), dtype=float)
    for t in range(T):
        emit_counts[int(obs_seq[t]), int(result[t])] += 1
    col_sums = emit_counts.sum(axis=0, keepdims=True)
    col_sums[col_sums == 0] = 1.0
    new_emission_probs = emit_counts / col_sums

    # Transition counts: how many times state i is followed by state j
    trans_counts = np.zeros((N, N), dtype=float)
    for idx in range(len(segments) - 1):
        trans_counts[segments[idx][0], segments[idx + 1][0]] += 1
    row_sums = trans_counts.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1.0
    new_trans_mat = trans_counts / row_sums

    # Duration counts: histogram of segment lengths per state, capped at D
    dur_counts = np.zeros((D, N), dtype=float)
    for s, _, length in segments:
        dur_counts[min(length, D) - 1, s] += 1
    col_sums = dur_counts.sum(axis=0, keepdims=True)
    col_sums[col_sums == 0] = 1.0
    new_duration_probs = dur_counts / col_sums

    # Start probs: deterministic from the first decoded segment
    new_start_probs = np.zeros(N, dtype=float)
    new_start_probs[segments[0][0]] = 1.0

    new_hsmm = copy.copy(gene_hsmm)
    new_hsmm.trans_mat              = new_trans_mat
    new_hsmm.emission_probs         = new_emission_probs
    new_hsmm.duration_probs         = new_duration_probs
    new_hsmm.duration_probs_linear  = new_duration_probs
    new_hsmm.start_probs            = new_start_probs
    return new_hsmm


def run_gene(gene_hsmm: HSMM, fasta_path: Path) -> None:

    N = len(gene_hsmm.states)
    T = len(gene_hsmm.obs_seq)
    D = gene_hsmm.duration_probs.shape[0]
    print(f"  states (N)={N}, timesteps (T)={T},  max duration (D)={D}\n")

    gene_hsmm.print_model()

    LEARNING_ITERATIONS = 1
    result = None
    for _ in range(LEARNING_ITERATIONS):

        gene_hsmm.to_log_space()

        t0 = time.perf_counter()
        result = decode_tensor_viterbi_omp(
            N, gene_hsmm.trans_mat, gene_hsmm.emission_probs,
            gene_hsmm.duration_probs_linear, gene_hsmm.start_probs,
            gene_hsmm.duration_probs, gene_hsmm.obs_seq,
        )
        elapsed = time.perf_counter() - t0

        n_intergenic = int(np.sum(result == 0))
        n_exon       = int(np.sum(result == 1))
        n_intron     = int(np.sum(result == 2))
        print(f"  time={elapsed:.4f} s  Intergenic={n_intergenic} ({100*n_intergenic/T:.2f}%)  Exon={n_exon} ({100*n_exon/T:.2f}%)  Intron={n_intron} ({100*n_intron/T:.2f}%)")
        print(f"  states[:10]={result[:10]}")

        gene_hsmm = reestimate_hsmm(gene_hsmm, result)

    if result is not None:
        out_path = fasta_path.with_suffix(".gene")
        write_gene(result, fasta_path, out_path)
        print(f"\nFinal result written → {out_path}")



if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--outdir", default=".", help="Output directory.")
    args = ap.parse_args()

    assembly = "hs1"  # T2T-CHM13 v2.0

    region = REGIONS[assembly]
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / f"{region['label']}.fa"

    if out_path.exists():
        print(f"[skip] {out_path} already exists, skipping download.", file=sys.stderr)
    else:
        seq = fetch_sequence(assembly,
                             region["chrom"], region["start"], region["end"])
        header = (f"{region['label']} "
                  f"{region['chrom']}:{region['start']}-{region['end']} "
                  f"len={len(seq)}")
        write_fasta(out_path, header, seq)

        n_count = seq.upper().count("N")
        print(f"[done] Wrote {out_path}", file=sys.stderr)
        print(f"[stats] length = {len(seq):,} bp", file=sys.stderr)
        print(f"[stats] Ns     = {n_count:,} ({100*n_count/len(seq):.2f}%)", file=sys.stderr)

    fasta_path = Path(__file__).parent / "T2T-CHM13v2.0_chrY_euchromatic_MSY.fa"
    gene_hsmm = gene_hsmm_loader(fasta_path, N=3, D=1000, limit=OBS_LIMIT)
    run_gene(gene_hsmm, fasta_path)
